### ISSUE TITLE
connection terminated immediately

### ISSUE THREAD

**Issue by PikuZheng** [kittoku/Open-SSTP-Client#113]
ver 1.6.5.1

disable "Add Trusted Certificates"
```
[2023-09-07 22:16:59.271] Establish VPN connection
[2023-09-07 22:17:16.354] OSC: ERR_UNEXPECTED
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:176)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at kittoku.osc.terminal.SSLTerminal.receive$app_release(SSLTerminal.kt:305)
	at kittoku.osc.client.incoming.IncomingClient$launchJobMain$1.invokeSuspend(IncomingClient.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

[2023-09-07 22:17:16.372] Terminate VPN connection
```

enable  "Add Trusted Certificates"
```
[2023-09-07 22:20:22.852] Establish VPN connection
[2023-09-07 22:20:22.891] OSC: ERR_UNEXPECTED
java.security.cert.CertificateException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
	at com.android.org.conscrypt.OpenSSLX509CertificateFactory.engineGenerateCertificate(OpenSSLX509CertificateFactory.java:311)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:366)
	at kittoku.osc.terminal.SSLTerminal.createTrustManagers(SSLTerminal.kt:82)
	at kittoku.osc.terminal.SSLTerminal.startHandshake(SSLTerminal.kt:99)
	at kittoku.osc.terminal.SSLTerminal.access$startHandshake(SSLTerminal.kt:37)
	at kittoku.osc.terminal.SSLTerminal$initialize$2.invokeSuspend(SSLTerminal.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
	at com.android.org.conscrypt.OpenSSLX509CertificateFactory$Parser.generateItem(OpenSSLX509CertificateFactory.java:147)
	at com.android.org.conscrypt.OpenSSLX509CertificateFactory.engineGenerateCertificate(OpenSSLX509CertificateFactory.java:309)
	... 13 more
Caused by: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
	at com.android.org.conscrypt.OpenSSLX509Certificate.fromX509DerInputStream(OpenSSLX509Certificate.java:103)
	at com.android.org.conscrypt.OpenSSLX509CertificateFactory$1.fromX509DerInputStream(OpenSSLX509CertificateFactory.java:261)
	at com.android.org.conscrypt.OpenSSLX509CertificateFactory$1.fromX509DerInputStream(OpenSSLX509CertificateFactory.java:251)
	at com.android.org.conscrypt.OpenSSLX509CertificateFactory$Parser.generateItem(OpenSSLX509CertificateFactory.java:137)
	... 14 more
Caused by: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
	at com.android.org.conscrypt.NativeCrypto.d2i_X509_bio(Native Method)
	at com.android.org.conscrypt.OpenSSLX509Certificate.fromX509DerInputStream(OpenSSLX509Certificate.java:97)
	... 17 more

[2023-09-07 22:20:22.894] Terminate VPN connection
```

**Comment by PikuZheng** [comment]
well. . . It doesn't seem to keep running, when switching to other software trying to test the network connection, the sstp process ends and the connection drops

**Comment by prounlocks** [comment]
i dont understand purpose of this app if its not working in background. Same issue. Its not only this app, this is android behavior. You just can bypass it implemented antisleep protector
