### ISSUE TITLE
1.8.0 Connection fails

### ISSUE THREAD

**Issue by cat174** [kittoku/Open-SSTP-Client#138]
Google Translate:
After the update, I cannot connect to the SSTP server on the keenetic router.
I suspect the PPP authentication method that came in the last update. That option is disabled, but I still suspect it breaks the other methods.

![resim](https://github.com/user-attachments/assets/6bddd5fb-03f5-47c1-a299-f97b1f0a3175)
![resim](https://github.com/user-attachments/assets/1ce72f87-dc88-4bbf-91e7-3cebcbd02d90)
![resim](https://github.com/user-attachments/assets/fe7131fc-a341-482b-8ad8-102864622074)
![resim](https://github.com/user-attachments/assets/561ac80f-7bc4-4642-b830-14e21d03fb43)
![resim](https://github.com/user-attachments/assets/0611915a-4d8b-4481-8e4e-36ad757fa314)

**Comment by kittoku** [comment]
Thank you for reporting. Could you upload the log?

**Comment by keyiflerolsun** [comment]
same error

```log
[2024-08-09 02:37:41.049] Establish VPN connection
[2024-08-09 02:37:46.018] OSC: ERR_UNEXPECTED
java.lang.ArrayIndexOutOfBoundsException: src.length=69 srcPos=0 dst.length=42 dstPos=0 length=69
	at java.lang.System.arraycopy(Native Method)
	at kotlin.collections.ArraysKt___ArraysJvmKt.copyInto(_ArraysJvm.kt:892)
	at kotlin.collections.ArraysKt___ArraysJvmKt.copyInto$default(_ArraysJvm.kt:891)
	at kittoku.osc.client.ppp.auth.MSCHAPV2Client.verifyAuthenticator$app_release(MSCHAPV2Client.kt:37)
	at kittoku.osc.client.ppp.auth.ChapMSCHAPV2Client.processResult(ChapMSCHAPV2Client.kt:29)
	at kittoku.osc.client.ppp.auth.ChapClient$launchJobAuth$1.invokeSuspend(ChapClient.kt:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

[2024-08-09 02:37:46.023] Terminate VPN connection
```

**Comment by cat174** [comment]
`[2024-08-09 09:06:37.470] Establish VPN connection
[2024-08-09 09:06:42.570] OSC: ERR_UNEXPECTED
java.lang.ArrayIndexOutOfBoundsException: src.length=69 srcPos=0 dst.length=42 dstPos=0 length=69
	at java.lang.System.arraycopy(Native Method)
	at kotlin.collections.ArraysKt___ArraysJvmKt.copyInto(_ArraysJvm.kt:892)
	at kotlin.collections.ArraysKt___ArraysJvmKt.copyInto$default(_ArraysJvm.kt:891)
	at kittoku.osc.client.ppp.auth.MSCHAPV2Client.verifyAuthenticator$app_release(MSCHAPV2Client.kt:37)
	at kittoku.osc.client.ppp.auth.ChapMSCHAPV2Client.processResult(ChapMSCHAPV2Client.kt:29)
	at kittoku.osc.client.ppp.auth.ChapClient$launchJobAuth$1.invokeSuspend(ChapClient.kt:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by kittoku** [comment]
Thank you all, @keyiflerolsun and @cat174 ! I think I found what caused the error.

Please wait for a patched release.

**Comment by kittoku** [comment]
Now I uploaded [v1.8.0.1 apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.8.0.1/osc-1.8.0.1.apk). In some days, it will be released as beta version at Google Play. 

Please try one of them.

**Comment by kittoku** [comment]
Google Play kindly accepted it already.

**Comment by cat174** [comment]
> Now I uploaded [v1.8.0.1 apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.8.0.1/osc-1.8.0.1.apk). In some days, it will be released as beta version at Google Play. 
> 
> Please try one of them.

Thank you for your prompt attention. I will install it when it is available on the Play Store and get back to you. I do not want to install an .apk file. 😘

**Comment by keyiflerolsun** [comment]
solved, Thank you 🕊

**Comment by cat174** [comment]
> Now I uploaded [v1.8.0.1 apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.8.0.1/osc-1.8.0.1.apk). In some days, it will be released as beta version at Google Play.
> 
> Please try one of them.
