### ISSUE TITLE
do not connect again 1.9.1

### ISSUE THREAD

**Issue by sifaaa** [kittoku/Open-SSTP-Client#150]
it used to work fine, but now it stopped connecting, no one made any changes =(

I'm attaching the logs

`[2024-10-20 22:56:36.683] Establish VPN connection
[2024-10-20 22:56:43.394] OSC: ERR_UNEXPECTED
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at kittoku.osc.terminal.SSLTerminal.receive$app_release(SSLTerminal.kt:428)
	at kittoku.osc.io.incoming.IncomingManager$launchJobMain$1.invokeSuspend(IncomingManager.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
`

(I'm using Google Translate)

**Comment by jamestyang2016** [comment]
Same issue, happened suddenly without any change on configuration.
