### ISSUE TITLE
1.6.2 disconnects within minutes after connecting to Windows Server SSTP

### ISSUE THREAD

**Issue by hstox** [kittoku/Open-SSTP-Client#83]
With 1.5.8 this worked fine. Now I get disconnects soon after connecting. Our company uses 2FA, so unfortunately I cannot use automatic reconnects. From the log file:

[2022-12-12 09:21:54.295] Establish VPN connection
[2022-12-12 09:22:06.628] OSC: ERR_UNEXPECTED
kotlin.UninitializedPropertyAccessException: lateinit property outputStream has not been initialized
	at kittoku.osc.terminal.IPTerminal.writePacket$app_release(IPTerminal.kt:146)
	at kittoku.osc.client.incoming.ProcessKt.processIPPacket(process.kt:213)
	at kittoku.osc.client.incoming.IncomingClient$launchJobMain$1.invokeSuspend(IncomingClient.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

[2022-12-12 09:22:06.646] Reconnection will be tried (LIFE = 2)
[2022-12-12 09:22:26.655] SSL: ERR_TIMEOUT
[2022-12-12 09:22:26.661] Reconnection will be tried (LIFE = 1)
[2022-12-12 09:22:46.673] SSL: ERR_TIMEOUT
[2022-12-12 09:22:46.679] Reconnection will be tried (LIFE = 0)
[2022-12-12 09:23:32.211] Terminate VPN connection

**Comment by kittoku** [comment]
Thank you for reporting. Maybe I found what caused your problem, but it will take some time to fix that.

Until this issue is fixed, please use [v1.5.8.1](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.5.8.1/osc-1.5.8.1.apk).

**Comment by tormentous** [comment]
This is exactly related to https://github.com/kittoku/Open-SSTP-Client/issues/57

**Comment by kittoku** [comment]
@hstox, could you test [osc-init.apk](https://github.com/kittoku/Open-SSTP-Client/releases/download/v1.6.2/osc-init.apk)?

**Comment by hstox** [comment]
Hi,

I won't put my Chromebook in developer mode, but I'll test it on my phone in 1 or 2 days.


-------- Oorspronkelijk bericht --------
Van: KOBAYASHI Ittoku ***@***.***>
Datum: 17-12-22 09:58 (GMT+01:00)
Aan: kittoku/Open-SSTP-Client ***@***.***>
Cc: Harry Stox ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [kittoku/Open-SSTP-Client] 1.6.2 disconnects within minutes after connecting to Windows Server SSTP (Issue #83)


@hstox<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhstox&data=05%7C01%7C%7C16b8f47354894437173508dae00ce907%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638068643289617715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M2%2F%2FXsRzWNBoG%2F%2FtnH6NOVAnf1pKOnI0IBBpaayh6GU%3D&reserved=0>, could you test osc-init.apk<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkittoku%2FOpen-SSTP-Client%2Freleases%2Fdownload%2Fv1.6.2%2Fosc-init.apk&data=05%7C01%7C%7C16b8f47354894437173508dae00ce907%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638068643289617715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vbSu%2F2MNCqXpoAaB8Vp2aEfUCq%2BdrtGCB0mXtSaLNEY%3D&reserved=0>?
